// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCku0F4u5HBCjmkicIb2xvYsQJsBkbZIdk',
    appId: '1:528150425076:web:7d1dd86dd9b6017f739da1',
    messagingSenderId: '528150425076',
    projectId: 'dalcioteca',
    authDomain: 'dalcioteca.firebaseapp.com',
    storageBucket: 'dalcioteca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDohWncedkc8t2y6rtt3ipT15Rysa_cCbA',
    appId: '1:528150425076:android:2a86aa9974345363739da1',
    messagingSenderId: '528150425076',
    projectId: 'dalcioteca',
    storageBucket: 'dalcioteca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfOsIEKCT21ItCjYJT5_cw0ZmIy5YezYg',
    appId: '1:528150425076:ios:484d2fd6e50378ff739da1',
    messagingSenderId: '528150425076',
    projectId: 'dalcioteca',
    storageBucket: 'dalcioteca.firebasestorage.app',
    iosBundleId: 'com.example.dalciotecaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfOsIEKCT21ItCjYJT5_cw0ZmIy5YezYg',
    appId: '1:528150425076:ios:484d2fd6e50378ff739da1',
    messagingSenderId: '528150425076',
    projectId: 'dalcioteca',
    storageBucket: 'dalcioteca.firebasestorage.app',
    iosBundleId: 'com.example.dalciotecaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCku0F4u5HBCjmkicIb2xvYsQJsBkbZIdk',
    appId: '1:528150425076:web:ee31fff1bf160ed9739da1',
    messagingSenderId: '528150425076',
    projectId: 'dalcioteca',
    authDomain: 'dalcioteca.firebaseapp.com',
    storageBucket: 'dalcioteca.firebasestorage.app',
  );
}
